package args

import "github.com/open-webtech/go-xaddy-config/schema/values"

// This file is autogenerated using "go generate ./schema/args". Do not modify, your changes will be lost.

const (
	Bool ValueType = iota
	String
	Uint
	Int
	Float32
	Float64
)

func BoolArg(target *bool, attributes ...ArgAttribute) *ArgDef {
	return NewArgDef(values.NewBoolValue(target), Bool, attributes...)
}

func VariadicBoolArg(target *[]bool, attributes ...ArgAttribute) *ArgDef {
	return NewVariadicArgDef(values.NewBoolsValue(target), Bool, attributes...)
}

func StringArg(target *string, attributes ...ArgAttribute) *ArgDef {
	return NewArgDef(values.NewStringValue(target), String, attributes...)
}

func VariadicStringArg(target *[]string, attributes ...ArgAttribute) *ArgDef {
	return NewVariadicArgDef(values.NewStringsValue(target), String, attributes...)
}

func UintArg(target *uint, attributes ...ArgAttribute) *ArgDef {
	return NewArgDef(values.NewUintValue(target), Uint, attributes...)
}

func VariadicUintArg(target *[]uint, attributes ...ArgAttribute) *ArgDef {
	return NewVariadicArgDef(values.NewUintsValue(target), Uint, attributes...)
}

func IntArg(target *int, attributes ...ArgAttribute) *ArgDef {
	return NewArgDef(values.NewIntValue(target), Int, attributes...)
}

func VariadicIntArg(target *[]int, attributes ...ArgAttribute) *ArgDef {
	return NewVariadicArgDef(values.NewIntsValue(target), Int, attributes...)
}

func Float32Arg(target *float32, attributes ...ArgAttribute) *ArgDef {
	return NewArgDef(values.NewFloat32Value(target), Float32, attributes...)
}

func VariadicFloat32Arg(target *[]float32, attributes ...ArgAttribute) *ArgDef {
	return NewVariadicArgDef(values.NewFloat32ListValue(target), Float32, attributes...)
}

func Float64Arg(target *float64, attributes ...ArgAttribute) *ArgDef {
	return NewArgDef(values.NewFloat64Value(target), Float64, attributes...)
}

func VariadicFloat64Arg(target *[]float64, attributes ...ArgAttribute) *ArgDef {
	return NewVariadicArgDef(values.NewFloat64ListValue(target), Float64, attributes...)
}
